[build]
  command = "npm run build"  # 构建命令（例如构建 React/Vue 项目）
  publish = "dist"           # 发布目录（构建后的文件所在目录）

# 环境变量（覆盖或设置部署时的环境变量）
[build.environment]
  NODE_VERSION = "16"        # 指定 Node.js 版本

# 重定向规则（将 URL 请求重定向到指定路径）
[[redirects]]
  from = "/old-path"         # 原始路径
  to = "/new-path"           # 目标路径
  status = 301               # HTTP 状态码（301 永久重定向）

# 分支部署配置（为不同 Git 分支设置不同的行为）
[context.deploy-preview]
  command = "npm run build:preview"  # 预览分支的构建命令

[context.production]
  publish = "dist/production"        # 生产分支的发布目录
